version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/flask-vue-crud
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      runas: ubuntu
      timeout: 300
  AfterInstall:
    - location: scripts/after-install.sh
      runas: root
      timeout: 30
  ApplicationStart:
    - location: scripts/restart.sh
      runas: ubuntu
      timeout: 600
  ValidateService:
    - location: scripts/initial.sh
      runas: ubuntu
      timeout: 600
