version: '3'
services:
  nginx:
    image: ${DOCKER_REGISTRY}/nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3000:3000'
      - '5000:5000'
  api:
    image: ${DOCKER_REGISTRY}/server
    build:
      dockerfile: Dockerfile
      context: ./server
  client:
    image: ${DOCKER_REGISTRY}/client
    build:
      dockerfile: Dockerfile
      context: ./client
