version: '3'
services:
  nginx:
    image: ${DOCKER_REGISTRY}/nginx:${BRANCH}
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3000:3000'
      - '5000:5000'
  api:
    image: ${DOCKER_REGISTRY}/server:${BRANCH}
    build:
      dockerfile: Dockerfile
      context: ./server
      args:
        ENV: ${BRANCH}
  client:
    image: ${DOCKER_REGISTRY}/client:${BRANCH}
    build:
      dockerfile: Dockerfile
      context: ./client
      args:
        ENV: ${BRANCH}
