version: '3'
services:
  nginx:
    image: flask-vue-crud_nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3000:3000'
      - '5000:5000'
  api:
    image: flask-vue-crud_api
    build:
      dockerfile: Dockerfile
      context: ./server
  client:
    image: flask-vue-crud_client
    build:
      dockerfile: Dockerfile
      context: ./client
