# status : sync with EDI engine
RESULT_STATUS_OK = "OK"
RESULT_STATUS_DATA = "DATA"
RESULT_STATUS_DEBUG = "DEBUG"
RESULT_STATUS_ERROR = "ERROR"
RESULT_STATUS_FATAL = "FATAL"

# proxy
PROXY_GROUP_RESIDENTIAL = "RESIDENTIAL"

# spider timeout
CLOSESPIDER_TIMEOUT = 60 * 20

# dummy
DUMMY_URL_DICT = {"google": "https://www.google.com"}
