# status : sync with EDI engine
RESULT_STATUS_OK = "OK"
RESULT_STATUS_DATA = "DATA"
RESULT_STATUS_DEBUG = "DEBUG"
RESULT_STATUS_ERROR = "ERROR"
RESULT_STATUS_FATAL = "FATAL"

# search_type
SEARCH_TYPE_AWB = "AWB"
SEARCH_TYPE_MBL = "MBL"
SEARCH_TYPE_BOOKING = "BOOKING"
SEARCH_TYPE_CONTAINER = "CONTAINER"

# proxy
PROXY_GROUP_RESIDENTIAL = "RESIDENTIAL"

# spider timeout
CLOSESPIDER_TIMEOUT = 60 * 20

# dummy
DUMMY_URL_DICT = {"eval_edi": "https://eval.edi.hardcoretech.co/c/livez"}
