# status : sync with EDI engine
TERMINAL_RESULT_STATUS_OK = 'OK'
TERMINAL_RESULT_STATUS_DATA = 'DATA'
TERMINAL_RESULT_STATUS_DEBUG = 'DEBUG'
TERMINAL_RESULT_STATUS_ERROR = 'ERROR'
TERMINAL_RESULT_STATUS_FATAL = 'FATAL'
