# status : sync with EDI engine
CARRIER_RESULT_STATUS_OK = 'OK'
CARRIER_RESULT_STATUS_DATA = 'DATA'
CARRIER_RESULT_STATUS_DEBUG = 'DEBUG'
CARRIER_RESULT_STATUS_ERROR = 'ERROR'
CARRIER_RESULT_STATUS_FATAL = 'FATAL'

# shipment_type: use in MblItem for spider
SHIPMENT_TYPE_MBL = 'MBL'
SHIPMENT_TYPE_BOOKING = 'BOOKING'
