name: Lint

on: [pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1024
      - uses: actions/setup-python@v2
      - name: pre-commit
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha}}
          HEAD_SHA: ${{ github.event.pull_request.head.sha}}
        run: |
          python -m pip install pre-commit
          # the bug for virualenv/setuptools/pip
          # ref: https://github.com/pypa/setuptools/issues/2353
          SETUPTOOLS_USE_DISTUTILS=stdlib pre-commit run --from-ref $BASE_SHA --to-ref $HEAD_SHA --all-files
      - name: gitlint
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha}}
          HEAD_SHA: ${{ github.event.pull_request.head.sha}}
        run: |
          pip install gitlint
          gitlint --commits "$BASE_SHA..$HEAD_SHA"
